#
# Makefile for the linux flatfs-filesystem routines.
#

obj-$(CONFIG_FLATFS_FS) += flatfs.o

flatfs-y := balloc.o bbuild.o brtree.o dir.o file.o inode.o namei.o super.o symlink.o ioctl.o journal.o flatfs_stats.o wprotect.o dax.o sysctl.o treeman.o namespace.o brbag.o ndcache.o
