#
# Makefile for the linux flatfs-filesystem routines.
#

obj-$(CONFIG_FLATFS_FS) += flatfs.o

flatfs-y := balloc.o bbuild.o brtree/ndcache.o brtree/bag.o brtree/sok.o brtree/node.o brtree/tree.o brtree/pslab.o dir.o file.o inode.o namei.o super.o symlink.o ioctl.o journal.o flatfs_stats.o wprotect.o dax.o sysctl.o namespace.o
